### ISSUE TITLE
2.0, 2.1 - no casting animation

### ISSUE THREAD

**Issue by dis9** [namreeb/nampower#16]
instant cast spells work fine and i do get an animation at the end of the cast but for the whole duration my character is just standing still as im casting. i tried version 2.0 and 2.1 and it happens on both. i disabled whatever addons i could think would mess with casting (lazypig, selfcast, ecastbar, classicsnowfall and ezdismount) but its still happening. got any clue why this is happening? im using the loader.exe directly from the WoW folder.

**Comment by namreeb** [comment]
I don't understand.  You're saying you are standing still for the duration of an instant cast spell?  Can you restate what is going on?

**Comment by dis9** [comment]
oops a lil tired lol. lets say im casting healing touch (druid) my character has no animations until the very end. so for 2.9 sec out of 3 sec my character is literally standing still in idle animation, while the healing touch sound is going. then at the very end she finally moves to play only the last part of the animation. meanwhile instant cast like rejuvination or even offensive instant spells like moonfire are fine. but anything with a cast time even wrath im completly idle until the last second.

**Comment by dis9** [comment]
and i should add that indeed if i lunch WoW normally without the loader all the animations are fine.

**Comment by hayleevee** [comment]
confirmed, the injector breaks spellcasting animations

**Comment by tetsugoro** [comment]
I have the same issue and it seems at least a few more people on Reddit and the Kronos Discord have it as well. [Here is a video with all addons disabled launched with loader.exe showing the problem.](https://my.mixtape.moe/qujsty.webm)
As you can see only spells with a normal cast time (including professions) never play their casting animations. Instant cast and channeled spells work fine.

**Comment by namreeb** [comment]
I think what is happening with this is the following:
1.  Cast spell #1, animation begins
2.  Cast time finished, nampower stops the animation thereby allowing the next cast
3.  Cast spell #2, animation begins
4.  The result of spell cast #1 arrives, stopping the current spell animation

If I understand correctly, this is strictly a visual issue, which I will categorize as a "wont fix".  The only way I can think to fix this would be to sometimes prevent a spell result from stopping the cast animation.  But only when the result is for the previous, rather than the current, spell cast.  And the question of which spell cast is the result for is difficult to answer.
